# Generated by Django 3.1 on 2020-08-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200815_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assets', to='app.profile'),
        ),
    ]
