# Generated by Django 3.1 on 2020-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200815_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
